import os
from dotenv import load_dotenv

load_dotenv()

AZURE_COSMOS_CONNECTION_STRING = os.getenv("AZURE_COSMOS_CONNECTION_STRING")
VISION_ENDPOINT = os.getenv("VISION_ENDPOINT")
VISION_KEY = os.getenv("VISION_KEY")
TEXT_TRANSLATION_ENDPOINT = os.getenv("TEXT_TRANSLATION_ENDPOINT")
TEXT_TRANSLATION_KEY = os.getenv("TEXT_TRANSLATION_KEY")

if AZURE_COSMOS_CONNECTION_STRING is None or VISION_ENDPOINT is None or VISION_KEY is None or TEXT_TRANSLATION_ENDPOINT is None or TEXT_TRANSLATION_KEY is None:
    raise Exception("AZURE_COSMOS_CONNECTION_STRING, VISION_ENDPOINT, VISION_KEY, TEXT_TRANSLATION_ENDPOINT, and TEXT_TRANSLATION_KEY environment variables must be set")

